- name: Install Java OpenJDK 21
  apt:
    name: openjdk-21-jdk
    state: present
  when: ansible_os_family == "Debian"

- name: verify installation of Java 21
  command: >
    java --version
  register: java_version

- name: Debug Java Version
  debug:
    msg: "{{ java_version.stdout_lines }}"
