---
# tasks file for jenkins
- include_tasks: 00_update_all_packages.yml
- include_tasks: 01_install_common_packages.yml
- include_tasks: 02_install_java_openjdk-12.yml
- include_tasks: 03_install_jenkins.yml
- include_tasks: 04_configure_jenkins.yml
