# === Update and Upgrade ===
- name: Update apt cache (Debian)
  apt:
    update_cache: yes
    cache_valid_time: 3600
  when: ansible_os_family == "Debian"

- name: Upgrade all packages (Debian)
  apt:
    upgrade: dist
  when: ansible_os_family == "Debian"
  ignore_errors: true
