- name: Install required packages for Docker Compose V2
  apt:
    name: docker-compose-plugin
    state: present
  when: ansible_os_family == 'Debian'  # Adjust package names for other package managers
